---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cluster-config
spec:
  interval: 30m
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cluster-config
  values:
    installCRDs: true
