---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux
    namespace: flux-system
  path: manifests/cert-manager
  prune: true
  wait: true
