---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: workloads
  namespace: cluster-config
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: clusters/workloads
  components:
    - northeurope
    - westeurope
  prune: true
  wait: false
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: workloads
