---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: capi-operator
  namespace: cluster-config
spec:
  interval: 30m
  url: https://kubernetes-sigs.github.io/cluster-api-operator
