---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${northeurope:name}
  namespace: capi-workload-clusters
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedControlPlane
    name: ${northeurope:name}
    namespace: capi-workload-clusters
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedCluster
    name: ${northeurope:name}
    namespace: capi-workload-clusters
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: ${northeurope:name}
  namespace: capi-workload-clusters
spec:
  clusterName: ${northeurope:name}
  replicas: 3
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: ${northeurope:name}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: ${northeurope:name}
        namespace: capi-workload-clusters
      version: v1.24.9
