---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedControlPlane
metadata:
  name: ${northeurope.name}
  namespace: capi-workload-clusters
spec:
  version: v1.24.9
  resourceGroupName: ${northeurope.resourceGroup}
  subscriptionID: ${global.name}
  location: northeurope
  sshPublicKey: ${northeurope.publicKey}
  networkPlugin: kubenet
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: ${northeurope.name}
    namespace: capi-workload-clusters
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedCluster
metadata:
  name: ${northeurope.name}
  namespace: capi-workload-clusters
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: ${northeurope.name}
  namespace: capi-workload-clusters
spec:
  mode: System
  sku: standard_d8s_v5
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  name: ${northeurope.name}
  namespace: capi-workload-clusters
spec:
  type: WorkloadIdentity
  clientID: ${global.clientId}
  tenantID: ${global.tenantId}
  allowedNamespaces:
    list:
      - capi-azure-system
      - capi-workload-clusters
