---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedControlPlane
metadata:
  name: ${north_europe_cluster_name}
  namespace: capi-workload-clusters
spec:
  version: v1.24.9
  resourceGroupName: ${global_resource_group}
  subscriptionID: ${global_subscription_id}
  location: northeurope
  sshPublicKey: ${global_public_key}
  networkPlugin: kubenet
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: ${north_europe_cluster_name}
    namespace: capi-workload-clusters
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedCluster
metadata:
  name: ${north_europe_cluster_name}
  namespace: capi-workload-clusters
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: ${north_europe_cluster_name}
  namespace: capi-workload-clusters
spec:
  mode: System
  sku: standard_d8s_v5
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  name: ${north_europe_cluster_name}
  namespace: capi-workload-clusters
spec:
  type: WorkloadIdentity
  clientID: ${global_client_id}
  tenantID: ${global_tenant_id}
  allowedNamespaces:
    list:
      - capi-azure-system
      - capi-workload-clusters
